// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MyTask.DAL;

public partial class Department : DomainObject
{
    public int Id { get; set; }
    public string Name { get; set; }
    [Required]
    public string Details { get; set; }
    [Required]
    public int Order { get; set; }
    [Required]
    public bool IsActive { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}