// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;

namespace MyTask.DAL;

public partial class Employee : DomainObject
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int Age { get; set; }
    public string NationalId { get; set; }
    public string Phone { get; set; }
    [Required]
    public string MobileNumber { get; set; }
    [Required]
    public bool IsActive { get; set; }
    [Required]
    public DateTime HiringDate { get; set; }
    [Required]
    public string Position { get; set; }
    public int? DepartmentId { get; set; }

    public virtual Department Department { get; set; }
}